/**
 * AI Content Provider Interface
 *
 * This module provides an abstraction for AI content generation.
 * Currently uses a mock provider, but can be swapped to OpenAI, Anthropic, etc.
 *
 * Configuration:
 * - AI_PROVIDER: 'mock' | 'openai' | 'anthropic' (default: 'mock')
 * - AI_API_KEY: API key for the provider
 * - AI_MODEL: Model to use (e.g., 'gpt-4', 'claude-3')
 */

export interface GenerateDraftOptions {
  topic: string;
  outline?: string;
  sourceUrl?: string;
  targetLength?: 'short' | 'medium' | 'long';
  tone?: 'professional' | 'casual' | 'technical';
  locale?: 'en' | 'vi';
}

export interface TranslateOptions {
  content: string;
  fromLocale: 'en' | 'vi';
  toLocale: 'en' | 'vi';
  preserveFormatting?: boolean;
}

export interface SummarizeOptions {
  content: string;
  maxLength?: number;
  style?: 'bullet' | 'paragraph';
}

export interface SeoOptimizeOptions {
  title: string;
  content: string;
  targetKeywords?: string[];
  locale?: 'en' | 'vi';
}

export interface AiContentResult {
  success: boolean;
  content?: string;
  metadata?: {
    title?: string;
    excerpt?: string;
    keywords?: string[];
    seoTitle?: string;
    seoDescription?: string;
  };
  error?: string;
  tokensUsed?: number;
}

export interface AiProvider {
  name: string;
  generateDraft(options: GenerateDraftOptions): Promise<AiContentResult>;
  translate(options: TranslateOptions): Promise<AiContentResult>;
  summarize(options: SummarizeOptions): Promise<AiContentResult>;
  seoOptimize(options: SeoOptimizeOptions): Promise<AiContentResult>;
}

/**
 * Mock AI Provider - Returns placeholder content for testing
 */
class MockAiProvider implements AiProvider {
  name = 'mock';

  async generateDraft(options: GenerateDraftOptions): Promise<AiContentResult> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const content = `
# ${options.topic}

This is a mock-generated article about "${options.topic}".

## Introduction

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

## Main Content

${options.outline || 'Here is the main content of the article based on the provided topic.'}

## Conclusion

In conclusion, this topic is very important and deserves further exploration.

---
*Generated by AI Assistant (Mock Provider)*
    `.trim();

    return {
      success: true,
      content,
      metadata: {
        title: options.topic,
        excerpt: `An article about ${options.topic}`,
        keywords: [options.topic.toLowerCase()],
        seoTitle: options.topic,
        seoDescription: `Learn more about ${options.topic} in this comprehensive article.`,
      },
    };
  }

  async translate(options: TranslateOptions): Promise<AiContentResult> {
    await new Promise((resolve) => setTimeout(resolve, 500));

    // Mock translation - just return the content with a note
    const translatedContent =
      options.toLocale === 'vi'
        ? `[Bản dịch tiếng Việt]\n\n${options.content}`
        : `[English Translation]\n\n${options.content}`;

    return {
      success: true,
      content: translatedContent,
    };
  }

  async summarize(options: SummarizeOptions): Promise<AiContentResult> {
    await new Promise((resolve) => setTimeout(resolve, 500));

    const summary =
      options.style === 'bullet'
        ? `• Key point 1 from the content\n• Key point 2 from the content\n• Key point 3 from the content`
        : `This is a summary of the provided content. The main points are covered in a concise manner.`;

    return {
      success: true,
      content: summary,
    };
  }

  async seoOptimize(options: SeoOptimizeOptions): Promise<AiContentResult> {
    await new Promise((resolve) => setTimeout(resolve, 500));

    return {
      success: true,
      content: options.content,
      metadata: {
        seoTitle: `${options.title} | Best Guide ${new Date().getFullYear()}`,
        seoDescription: `Discover everything about ${options.title}. Comprehensive guide with tips and insights.`,
        keywords: options.targetKeywords || [options.title.toLowerCase()],
      },
    };
  }
}

/**
 * Get the configured AI provider
 */
export function getAiProvider(): AiProvider {
  const providerName = process.env.AI_PROVIDER || 'mock';

  switch (providerName) {
    case 'openai':
      // TODO: Implement OpenAI provider
      console.warn('OpenAI provider not implemented, falling back to mock');
      return new MockAiProvider();

    case 'anthropic':
      // TODO: Implement Anthropic provider
      console.warn('Anthropic provider not implemented, falling back to mock');
      return new MockAiProvider();

    case 'mock':
    default:
      return new MockAiProvider();
  }
}

/**
 * Create an AI content job record
 */
export async function createAiJob(
  type: 'GENERATE_DRAFT' | 'TRANSLATE' | 'SUMMARIZE' | 'SEO_OPTIMIZE' | 'REWRITE',
  input: Record<string, unknown>,
  postId?: string,
  locale?: string,
  createdBy?: string
) {
  const { prisma } = await import('@/lib/db');

  return prisma.aiContentJob.create({
    data: {
      type,
      status: 'QUEUED',
      input: JSON.stringify(input),
      postId,
      locale,
      createdBy,
    },
  });
}

/**
 * Update an AI job status
 */
export async function updateAiJob(
  jobId: string,
  status: 'RUNNING' | 'DONE' | 'FAILED',
  output?: Record<string, unknown>,
  error?: string
) {
  const { prisma } = await import('@/lib/db');

  return prisma.aiContentJob.update({
    where: { id: jobId },
    data: {
      status,
      output: output ? JSON.stringify(output) : undefined,
      error,
    },
  });
}
