/**
 * Standardized Error Codes for Creative Engineering Platform
 * 
 * These codes are used across all API responses for consistent error handling.
 * Format: DOMAIN_SPECIFIC_ERROR
 */

export const ErrorCode = {
  // Authentication & Authorization
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',

  // Resource
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Business Logic
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_ALREADY_PROCESSED: 'ORDER_ALREADY_PROCESSED',
  CHECKOUT_EMPTY_CART: 'CHECKOUT_EMPTY_CART',
  CHECKOUT_PRODUCT_NOT_FOUND: 'CHECKOUT_PRODUCT_NOT_FOUND',
  CHECKOUT_INSUFFICIENT_STOCK: 'CHECKOUT_INSUFFICIENT_STOCK',
  CHECKOUT_DUPLICATE: 'CHECKOUT_DUPLICATE',

  // Inventory
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_DOCUMENT_ALREADY_POSTED: 'INVENTORY_DOCUMENT_ALREADY_POSTED',
  INVENTORY_DOCUMENT_VOID_NOT_ALLOWED: 'INVENTORY_DOCUMENT_VOID_NOT_ALLOWED',
  INVENTORY_INVALID_QUANTITY: 'INVENTORY_INVALID_QUANTITY',

  // Payment
  PAYMENT_INVALID_AMOUNT: 'PAYMENT_INVALID_AMOUNT',
  PAYMENT_EXCEEDS_OUTSTANDING: 'PAYMENT_EXCEEDS_OUTSTANDING',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * HTTP status codes mapped to error codes
 */
export const ErrorHttpStatus: Record<ErrorCodeType, number> = {
  // 401 Unauthorized
  [ErrorCode.AUTH_REQUIRED]: 401,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,

  // 403 Forbidden
  [ErrorCode.AUTH_FORBIDDEN]: 403,
  [ErrorCode.AUTH_INSUFFICIENT_ROLE]: 403,

  // 400 Bad Request
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.VALIDATION_REQUIRED_FIELD]: 400,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 400,
  [ErrorCode.CHECKOUT_EMPTY_CART]: 400,
  [ErrorCode.INVENTORY_INVALID_QUANTITY]: 400,
  [ErrorCode.PAYMENT_INVALID_AMOUNT]: 400,

  // 404 Not Found
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.CHECKOUT_PRODUCT_NOT_FOUND]: 404,

  // 409 Conflict
  [ErrorCode.ALREADY_EXISTS]: 409,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.ORDER_INVALID_TRANSITION]: 409,
  [ErrorCode.ORDER_ALREADY_PROCESSED]: 409,
  [ErrorCode.CHECKOUT_DUPLICATE]: 409,
  [ErrorCode.CHECKOUT_INSUFFICIENT_STOCK]: 409,
  [ErrorCode.INVENTORY_INSUFFICIENT_STOCK]: 409,
  [ErrorCode.INVENTORY_DOCUMENT_ALREADY_POSTED]: 409,
  [ErrorCode.INVENTORY_DOCUMENT_VOID_NOT_ALLOWED]: 409,
  [ErrorCode.PAYMENT_EXCEEDS_OUTSTANDING]: 409,

  // 429 Too Many Requests
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,

  // 500 Internal Server Error
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
};

